import { createFileRoute } from '@tanstack/react-router';
import { MapPin, Instagram } from 'lucide-react';
import { SiteLayout, PageHeader } from '@/components/site/SiteLayout';
import { PageError } from '@/components/site/PageError';
import { siteQuery, siteMeta, useSiteContent } from '@/lib/site-query';
import { safeLink } from '@/lib/site-content';
import { Button } from '@/components/ui/button';
export const Route = createFileRoute('/contato')({loader: ({context}) => context.queryClient.ensureQueryData(siteQuery), head: ({loaderData:c}) => siteMeta(`${c?.navContact ?? 'Contato'} — ${c?.name ?? 'Comunidade Aava'}`, `Encontre ${c?.name ?? 'a comunidade'} em ${c?.city ?? 'Jacareí'}.`), errorComponent: PageError, notFoundComponent: PageError, component: Contact});
function Contact(){const c=useSiteContent();const q=encodeURIComponent(c.mapsQuery);return <SiteLayout><PageHeader eyebrow={c.contactEyebrow} title={c.contactTitle} text={c.contactText}/><section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-[1fr_1.5fr] lg:px-10"><div className="space-y-8"><div className="flex gap-3"><MapPin className="h-5 w-5 shrink-0 text-primary"/><div><h2 className="text-lg">{c.addressLabel}</h2><p className="mt-3 text-muted-foreground">{c.address}<br/>{c.city}</p><Button asChild variant="link" className="mt-2 px-0"><a href={`https://www.google.com/maps/search/?api=1&query=${q}`} target="_blank" rel="noreferrer">{c.mapsLabel} →</a></Button></div></div>{c.phone && <p>{c.phone}</p>}{c.email && <p>{c.email}</p>}{safeLink(c.instagramUrl) && <div><h2 className="text-lg">{c.socialLabel}</h2><Button asChild variant="outline" className="mt-3"><a href={safeLink(c.instagramUrl)} target="_blank" rel="noreferrer"><Instagram/>Instagram</a></Button></div>}</div><iframe title="Mapa da igreja" className="h-80 w-full border" loading="lazy" src={`https://www.google.com/maps?q=${q}&output=embed`}/></section></SiteLayout>}
