import { createFileRoute } from '@tanstack/react-router';
import { Copy, ArrowUpRight, Heart } from 'lucide-react';
import { toast } from 'sonner';
import { SiteLayout, PageHeader } from '@/components/site/SiteLayout';
import { PageError } from '@/components/site/PageError';
import { Button } from '@/components/ui/button';
import { siteQuery, siteMeta, useSiteContent } from '@/lib/site-query';
import { safeLink } from '@/lib/site-content';
export const Route=createFileRoute('/contribuicao')({loader:({context})=>context.queryClient.ensureQueryData(siteQuery),head:({loaderData:c})=>siteMeta(`${c?.contributionTitle ?? 'Contribuição'} — ${c?.name ?? 'Comunidade Aava'}`,c?.contributionText ?? 'Formas de contribuir com a comunidade.'),errorComponent:PageError,notFoundComponent:PageError,component:Contribution});
function Contribution(){const c=useSiteContent();return <SiteLayout><PageHeader eyebrow={c.contributionEyebrow} title={c.contributionTitle} text={c.contributionText}/><div className="mx-auto max-w-7xl space-y-12 px-5 py-16 lg:px-10">{c.pixKeys.length>0 && <section><h2 className="mb-6 text-2xl">{c.pixTitle}</h2><div className="grid gap-5 md:grid-cols-2">{c.pixKeys.map((pix,i)=><div key={i} className="rounded-md border bg-card p-6"><Heart className="h-6 w-6 text-primary"/><h3 className="mt-4 text-lg">{pix.label || 'Pix'}</h3>{pix.recipient && <p className="mt-2 text-sm text-muted-foreground">{pix.recipient}</p>}<p className="mt-4 break-all font-mono text-lg">{pix.key}</p><Button className="mt-5" variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(pix.key);toast.success('Chave Pix copiada');}catch{toast.error('Não foi possível copiar. Selecione a chave acima.');}}}><Copy/>Copiar chave Pix</Button></div>)}</div></section>}{c.methods.length>0 && <section><h2 className="mb-6 text-2xl">{c.methodsTitle}</h2><div className="grid gap-5 md:grid-cols-2">{c.methods.map((method,i)=><div key={i} className="rounded-md border p-6"><h3 className="text-lg">{method.title}</h3><p className="mt-3 whitespace-pre-wrap text-muted-foreground">{method.details}</p>{safeLink(method.url)&&<Button asChild className="mt-5"><a href={safeLink(method.url)} target="_blank" rel="noreferrer">{method.title}<ArrowUpRight/></a></Button>}</div>)}</div></section>}{!c.pixKeys.length&&!c.methods.length&&<p className="text-muted-foreground">{c.contributionEmpty}</p>}</div></SiteLayout>}