/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ContribuicaoRouteImport } from './routes/contribuicao'
import { Route as CultosRouteImport } from './routes/cultos'
import { Route as OracaoRouteImport } from './routes/oracao'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as ConviteCodeRouteImport } from './routes/convite.$code'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelFinanceiroRouteImport } from './routes/_authenticated/painel.financeiro'
import { Route as AuthenticatedPainelMembrosRouteImport } from './routes/_authenticated/painel.membros'
import { Route as AuthenticatedPainelMeuCadastroRouteImport } from './routes/_authenticated/painel.meu-cadastro'
import { Route as AuthenticatedPainelOracaoRouteImport } from './routes/_authenticated/painel.oracao'
import { Route as AuthenticatedPainelPermissoesRouteImport } from './routes/_authenticated/painel.permissoes'
import { Route as AuthenticatedPainelRelatorioRouteImport } from './routes/_authenticated/painel.relatorio'
import { Route as AuthenticatedPainelSiteRouteImport } from './routes/_authenticated/painel.site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContribuicaoRoute = ContribuicaoRouteImport.update({
  id: '/contribuicao',
  path: '/contribuicao',
  getParentRoute: () => rootRouteImport,
} as any)
const CultosRoute = CultosRouteImport.update({
  id: '/cultos',
  path: '/cultos',
  getParentRoute: () => rootRouteImport,
} as any)
const OracaoRoute = OracaoRouteImport.update({
  id: '/oracao',
  path: '/oracao',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteCodeRoute = ConviteCodeRouteImport.update({
  id: '/convite/$code',
  path: '/convite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelFinanceiroRoute =
  AuthenticatedPainelFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelMembrosRoute =
  AuthenticatedPainelMembrosRouteImport.update({
    id: '/membros',
    path: '/membros',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelMeuCadastroRoute =
  AuthenticatedPainelMeuCadastroRouteImport.update({
    id: '/meu-cadastro',
    path: '/meu-cadastro',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelOracaoRoute =
  AuthenticatedPainelOracaoRouteImport.update({
    id: '/oracao',
    path: '/oracao',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPermissoesRoute =
  AuthenticatedPainelPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelRelatorioRoute =
  AuthenticatedPainelRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelSiteRoute = AuthenticatedPainelSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/contribuicao': typeof ContribuicaoRoute
  '/cultos': typeof CultosRoute
  '/oracao': typeof OracaoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/convite/$code': typeof ConviteCodeRoute
  '/painel/financeiro': typeof AuthenticatedPainelFinanceiroRoute
  '/painel/membros': typeof AuthenticatedPainelMembrosRoute
  '/painel/meu-cadastro': typeof AuthenticatedPainelMeuCadastroRoute
  '/painel/oracao': typeof AuthenticatedPainelOracaoRoute
  '/painel/permissoes': typeof AuthenticatedPainelPermissoesRoute
  '/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/painel/site': typeof AuthenticatedPainelSiteRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/contribuicao': typeof ContribuicaoRoute
  '/cultos': typeof CultosRoute
  '/oracao': typeof OracaoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/convite/$code': typeof ConviteCodeRoute
  '/painel/financeiro': typeof AuthenticatedPainelFinanceiroRoute
  '/painel/membros': typeof AuthenticatedPainelMembrosRoute
  '/painel/meu-cadastro': typeof AuthenticatedPainelMeuCadastroRoute
  '/painel/oracao': typeof AuthenticatedPainelOracaoRoute
  '/painel/permissoes': typeof AuthenticatedPainelPermissoesRoute
  '/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/painel/site': typeof AuthenticatedPainelSiteRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/contribuicao': typeof ContribuicaoRoute
  '/cultos': typeof CultosRoute
  '/oracao': typeof OracaoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/convite/$code': typeof ConviteCodeRoute
  '/_authenticated/painel/financeiro': typeof AuthenticatedPainelFinanceiroRoute
  '/_authenticated/painel/membros': typeof AuthenticatedPainelMembrosRoute
  '/_authenticated/painel/meu-cadastro': typeof AuthenticatedPainelMeuCadastroRoute
  '/_authenticated/painel/oracao': typeof AuthenticatedPainelOracaoRoute
  '/_authenticated/painel/permissoes': typeof AuthenticatedPainelPermissoesRoute
  '/_authenticated/painel/relatorio': typeof AuthenticatedPainelRelatorioRoute
  '/_authenticated/painel/site': typeof AuthenticatedPainelSiteRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/contribuicao'
    | '/cultos'
    | '/oracao'
    | '/quem-somos'
    | '/painel'
    | '/convite/$code'
    | '/painel/financeiro'
    | '/painel/membros'
    | '/painel/meu-cadastro'
    | '/painel/oracao'
    | '/painel/permissoes'
    | '/painel/relatorio'
    | '/painel/site'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/contribuicao'
    | '/cultos'
    | '/oracao'
    | '/quem-somos'
    | '/convite/$code'
    | '/painel/financeiro'
    | '/painel/membros'
    | '/painel/meu-cadastro'
    | '/painel/oracao'
    | '/painel/permissoes'
    | '/painel/relatorio'
    | '/painel/site'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/contribuicao'
    | '/cultos'
    | '/oracao'
    | '/quem-somos'
    | '/_authenticated/painel'
    | '/convite/$code'
    | '/_authenticated/painel/financeiro'
    | '/_authenticated/painel/membros'
    | '/_authenticated/painel/meu-cadastro'
    | '/_authenticated/painel/oracao'
    | '/_authenticated/painel/permissoes'
    | '/_authenticated/painel/relatorio'
    | '/_authenticated/painel/site'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  ContribuicaoRoute: typeof ContribuicaoRoute
  CultosRoute: typeof CultosRoute
  OracaoRoute: typeof OracaoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ConviteCodeRoute: typeof ConviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribuicao': {
      id: '/contribuicao'
      path: '/contribuicao'
      fullPath: '/contribuicao'
      preLoaderRoute: typeof ContribuicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultos': {
      id: '/cultos'
      path: '/cultos'
      fullPath: '/cultos'
      preLoaderRoute: typeof CultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracao': {
      id: '/oracao'
      path: '/oracao'
      fullPath: '/oracao'
      preLoaderRoute: typeof OracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$code': {
      id: '/convite/$code'
      path: '/convite/$code'
      fullPath: '/convite/$code'
      preLoaderRoute: typeof ConviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/financeiro': {
      id: '/_authenticated/painel/financeiro'
      path: '/financeiro'
      fullPath: '/painel/financeiro'
      preLoaderRoute: typeof AuthenticatedPainelFinanceiroRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/membros': {
      id: '/_authenticated/painel/membros'
      path: '/membros'
      fullPath: '/painel/membros'
      preLoaderRoute: typeof AuthenticatedPainelMembrosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/meu-cadastro': {
      id: '/_authenticated/painel/meu-cadastro'
      path: '/meu-cadastro'
      fullPath: '/painel/meu-cadastro'
      preLoaderRoute: typeof AuthenticatedPainelMeuCadastroRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/oracao': {
      id: '/_authenticated/painel/oracao'
      path: '/oracao'
      fullPath: '/painel/oracao'
      preLoaderRoute: typeof AuthenticatedPainelOracaoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/permissoes': {
      id: '/_authenticated/painel/permissoes'
      path: '/permissoes'
      fullPath: '/painel/permissoes'
      preLoaderRoute: typeof AuthenticatedPainelPermissoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/relatorio': {
      id: '/_authenticated/painel/relatorio'
      path: '/relatorio'
      fullPath: '/painel/relatorio'
      preLoaderRoute: typeof AuthenticatedPainelRelatorioRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/site': {
      id: '/_authenticated/painel/site'
      path: '/site'
      fullPath: '/painel/site'
      preLoaderRoute: typeof AuthenticatedPainelSiteRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelFinanceiroRoute: typeof AuthenticatedPainelFinanceiroRoute
  AuthenticatedPainelMembrosRoute: typeof AuthenticatedPainelMembrosRoute
  AuthenticatedPainelMeuCadastroRoute: typeof AuthenticatedPainelMeuCadastroRoute
  AuthenticatedPainelOracaoRoute: typeof AuthenticatedPainelOracaoRoute
  AuthenticatedPainelPermissoesRoute: typeof AuthenticatedPainelPermissoesRoute
  AuthenticatedPainelRelatorioRoute: typeof AuthenticatedPainelRelatorioRoute
  AuthenticatedPainelSiteRoute: typeof AuthenticatedPainelSiteRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelFinanceiroRoute: AuthenticatedPainelFinanceiroRoute,
  AuthenticatedPainelMembrosRoute: AuthenticatedPainelMembrosRoute,
  AuthenticatedPainelMeuCadastroRoute: AuthenticatedPainelMeuCadastroRoute,
  AuthenticatedPainelOracaoRoute: AuthenticatedPainelOracaoRoute,
  AuthenticatedPainelPermissoesRoute: AuthenticatedPainelPermissoesRoute,
  AuthenticatedPainelRelatorioRoute: AuthenticatedPainelRelatorioRoute,
  AuthenticatedPainelSiteRoute: AuthenticatedPainelSiteRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  ContribuicaoRoute: ContribuicaoRoute,
  CultosRoute: CultosRoute,
  OracaoRoute: OracaoRoute,
  QuemSomosRoute: QuemSomosRoute,
  ConviteCodeRoute: ConviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
